export const Catalogue = [
  {
    name: "Eco-Friendly Bamboo Toothbrush Set",
    description:
      "A sustainable, biodegradable toothbrush set with various bristle hardness options, perfect for eco-conscious buyers.",
    id: 0,
    imageURL: "../Image-repo/download.png",
    inStock: 25,
    sold: 26,
    price: 2.49,
    retailPrice: 12.99,
    extratax: true,
    countryoforigin: "Vietnam",
    placeofOrgin: "N/A",
    inpack: 4,
  },
  {
    name: "Portable Bluetooth Speaker with LED Lights",
    description:
      "A compact, waterproof Bluetooth speaker that comes with customizable LED lights for outdoor gatherings or parties.",
    id: 1,
    imageURL: "../Image-repo/download.png",
    inStock: 15,
    sold: 3,
    price: 15.99,
    retailPrice: 39.99,
    extratax: true,
    countryoforigin: "Republic of China (ROC)",
    placeofOrgin: "N/A",
    inpack: 1,
  },
  {
    name: "Personalized Leather Journal",
    description:
      "A high-quality leather-bound journal that can be engraved with custom names or messages, perfect for writers or travelers.",
    id: 2,
    imageURL: "./Images/download.png",
    inStock: 29,
    sold: 26,
    price: 7.58,
    retailPrice: 29.99,
    extratax: false,
    countryoforigin: "Germany",
    placeofOrgin: "Düsseldorf, Nordrhein-Westfalen",

    inpack: 1,
  },
  {
    name: "Collapsible Reusable Silicone Coffee Cup",
    description:
      "A space-saving, eco-friendly coffee cup made of food-grade silicone, ideal for commuters or anyone who wants to reduce waste.",
    id: 3,
    imageURL: "./Images/download.png",
    inStock: 0,
    sold: 90,
    price: 4.64,
    retailPrice: 14.99,
    extratax: true,
    countryoforigin: "Peoples Republic of China (PRC)",
    placeofOrgin: "N/A",
    inpack: 4,
  },
  {
    name: "DIY Terrarium Kit",
    description:
      "A complete terrarium kit with all the materials needed to build your own little indoor garden, including decorative rocks and plants.",
    id: 4,
    imageURL: "./Images/download.png",
    inStock: 3,
    sold: 27,
    price: 19.99,
    retailPrice: 29.99,
    extratax: false,
    countryoforigin: " Ukraine",
    placeofOrgin: "Kyiv, Kyiv Region",
    inpack: 1,
  },
  {
    name: "Smart Water Bottle with Hydration Reminders",
    description:
      "A sleek, insulated water bottle with a built-in reminder system that tracks water intake and notifies you when it`s time to hydrate.",
    id: 5,
    imageURL: "./Images/download.png",
    inStock: 37,
    sold: 3,
    price: 12.56,
    retailPrice: 34.99,
    extratax: true,
    countryoforigin: "United States (USA)",
    placeofOrgin: "Birmingham, Alabama",
    inpack: 1,
  },
  {
    name: "Wireless Earbuds (Bluetooth)",
    description:
      "Compact and comfortable wireless earbuds with high-quality sound, noise cancellation, and a long-lasting battery. Ideal for workouts and daily commuting.",
    id: 6,
    imageURL: "./Images/download.png",
    inStock: 37,
    sold: 3,
    price: 25.35,
    retailPrice: 49.99,
    extratax: true,
    countryoforigin: "Norway",
    placeofOrgin: "Oslo,Oslo County ",
    inpack: 1,
  },
  {
    name: "Portable Solar Charger",
    description:
      "Eco-friendly solar charger for your devices, perfect for camping, outdoor activities, or emergencies. Features fast-charging capabilities and rugged design.",
    id: 7,
    imageURL: "./Images/download.png",
    inStock: 0,
    sold: 12,
    price: 15.5,
    retailPrice: 39.99,
    extratax: true,
    countryoforigin: "Peoples Republic of China (PRC)",
    placeofOrgin: "N/A",
    inpack: 1,
  },
  {
    name: "Smartphone Stand & Holder",
    description:
      "Adjustable and durable stand for smartphones, designed for video calls, watching media, or hands-free use. Compatible with most devices.",
    id: 8,
    imageURL: "./Images/download.png",
    inStock: 37,
    sold: 23,
    price: 6.56,
    retailPrice: 14.99,
    extratax: true,
    countryoforigin: "Peoples Republic of China (PRC)",
    placeofOrgin: "N/A",
    inpack: 4,
  },
  {
    name: "Ergonomic Memory Foam Pillow",
    description:
      "A premium-quality memory foam pillow designed to support neck and spine alignment for a restful sleep.",
    id: 9,
    imageURL: "./Images/download.png",
    inStock: 20,
    sold: 20,
    price: 22.99,
    retailPrice: 49.99,
    extratax: true,
    countryoforigin: "Canada",
    placeofOrgin: "Toronto, Ontario",
    inpack: 1,
  },
  {
    name: "Mini Desk Air Purifier",
    description:
      "A compact and efficient air purifier designed for small spaces, removing dust, allergens, and pollutants.",
    id: 10,
    imageURL: "./Images/download.png",
    inStock: 10,
    sold: 0,
    price: 29.99,
    retailPrice: 59.99,
    extratax: true,
    countryoforigin: "Japan",
    placeofOrgin: "Tokyo, Kanto Region",
    inpack: 1,
  },
  {
    name: "Smart LED Light Bulb (Wi-Fi Enabled)",
    description:
      "A color-changing, energy-efficient LED bulb controlled via an app or voice assistant.",
    id: 11,
    imageURL: "./Images/download.png",
    inStock: 50,
    sold: 0,
    price: 9.99,
    retailPrice: 24.99,
    extratax: true,
    countryoforigin: "South Korea (ROK)",
    placeofOrgin: "N/A",
    inpack: 2,
  },
  {
    name: "Cordless Handheld Vacuum Cleaner",
    description:
      "A lightweight, rechargeable vacuum for quick cleanups at home, in the office, or in your car.",
    id: 12,
    imageURL: "./Images/download.png",
    inStock: 12,
    sold: 6,
    price: 35.99,
    retailPrice: 69.99,
    extratax: true,
    countryoforigin: "Germany",
    placeofOrgin: "Berlin, Brandenburg",
    inpack: 1,
  },
  {
    name: "Luxury Soy Wax Scented Candle",
    description:
      "A long-lasting, hand-poured soy wax candle with soothing fragrances, perfect for relaxation and ambiance.",
    id: 13,
    imageURL: "./Images/download.png",
    inStock: 30,
    sold: 10,
    price: 14.99,
    retailPrice: 29.99,
    extratax: false,
    countryoforigin: "France",
    placeofOrgin: "Paris, Île-de-France",
    inpack: 1,
  },
];
/*
Item type:Add item
{

  name: "",
  description: "",
  id: 0,
  imageURL: "none",
  inStock: 0,
  price: 0,
  retailPrice:,
  itemtype:0,
   extratax: true,
    countryoforigin: "",
    inpack: 0,
}
  */
/*
item type: List of diffrent itemtype Categorys
0 = placeholder
1 = electronics
2 = books
3 = office
4 = 
*/
